# Parts of this file are based on:
#   url: https://github.com/al3x/sovereign/blob/a48a9941009cc1f18450d01cc7cf4f067ece3fae/roles/tarsnap/tasks/tarsnap.yml
#   contributors:  al3x jplock lvillani lukecyca jsravn bcachet alexdunae pdebruic
# The sovereign project source and this derivative work are licensed under the GNU General Public License v3.

- name: Apt-install dependencies for Tarsnap
  apt: pkg={{ item }} state=installed
  with_items:
    - e2fslibs-dev
    - libssl-dev
    - zlib1g-dev
    - build-essential
    - python-setuptools
  when: ansible_pkg_mgr | lower == "apt"

- name: Yum-install dependencies for Tarsnap
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - make
    - glibc-devel
    - openssl-devel
    - zlib-devel
    - e2fsprogs-devel
  when: ansible_pkg_mgr | lower == "yum"

- name: Check if tarsnap {{ tarsnap_version }} is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarnsap_installed
  changed_when: "tarnsap_installed.stderr != ''"
  ignore_errors: yes

- include: tarsnap_install.yml
  when: tarnsap_installed|failed

- name: Create Tarsnap cache directory
  file: state=directory path={{ tarsnap_cache }}

- name: Install tarsnapper wrapper
  easy_install: name=tarsnapper

- name: Install tarsnapper configuration file
  copy: src={{ tarsnap_tarsnapper_conf }} dest=/root/tarsnapper.conf mode=0644

- name: Install Tarsnap configuration file
  template: src=tarsnaprc.j2 dest=/root/.tarsnaprc mode=0644

- name: Install tarsnapper backup script
  copy: src=tarsnap.sh dest=/root/tarsnap.sh mode=0755

- name: Configure tarsnap logrotate
  copy: src=etc_logrotate_tarsnap dest=/etc/logrotate.d/tarsnap owner=root group=root mode=0644

- name: Install nightly Tarsnap-generations cronjob
  cron:
  args:
    name: "Tarsnap backup"
    job: "/root/tarsnap.sh > /dev/null"
    minute: "{{ tarsnap_cron_minute }}"
    hour: "{{ tarsnap_cron_hour }}"
    day: "{{ tarsnap_cron_day }}"
    month: "{{ tarsnap_cron_month }}"
