# Parts of this file are based on:
#   url: https://github.com/al3x/sovereign/blob/a48a9941009cc1f18450d01cc7cf4f067ece3fae/roles/tarsnap/tasks/tarsnap.yml
#   contributors:  al3x jplock lvillani lukecyca jsravn bcachet alexdunae pdebruic
# The sovereign project source and this derivative work are licensed under the GNU General Public License v3.

- name: Apt-install dependencies for Tarsnap
  apt: pkg={{ item }} state=installed
  with_items:
    - e2fslibs-dev
    - libssl-dev
    - zlib1g-dev
    - build-essential
    - python-setuptools
  when: ansible_pkg_mgr | lower == "apt"

- name: Yum-install dependencies for Tarsnap
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - make
    - glibc-devel
    - openssl-devel
    - zlib-devel
    - e2fsprogs-devel
  when: ansible_pkg_mgr | lower == "yum"

- name: Check if tarsnap {{ tarsnap_version }} is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarnsap_installed
  changed_when: "tarnsap_installed.stderr != ''"
  ignore_errors: yes

- include: tarsnap_install.yml
  when: tarnsap_installed|failed

- include: tarsnap_configure.yml
  when: tarsnap_install_only == false
